version: "3"
services:
  db:
    container_name: pg-prod
    image: postgres
    networks:
      - cep-network
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres

  poc-cep:
    container_name: poc-cep
    image: victormacedo400/cep
    networks:
      - cep-network
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db

networks:
  cep-network: